# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3c0a3cc1de6d05549613e25ae8758e0ca614156a04b8d05432e16ad9425a7850713247bc6fa3aaa6783e32aa17532fb33726c7832bc358b37d17d9a57f3c3ac9

test:
  secret_key_base: e17daf4ca8ea0b8c1d4c9077428bc4c7d25c59bd5281c0a77a2cfda85d4f2605ccc1445c494384ecbac20a16e281956f9e753fb156c63205ea2c85347c393f8a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
